export const SIMULATION_TICK_SECONDS = 3;
export const STARVATION_CONSEQUENCE_TICKS = 3;
export const POPULATION_GROWTH_TICKS = 3;
export const BUILDING_DEGRADATION_TICKS = 20;
export const PRODUCTION_DEGRADATION_TICKS = 20;