name: Build and Publish Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          OWNER="abnocchinwads"
          REPO="resource-management-game"

          IMAGE="ghcr.io/${OWNER}/${REPO}:${GITHUB_SHA}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')

          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Trigger deploy
        run: |
          curl -X POST https://api.github.com/repos/abnocchinwads/home-server/dispatches \
          -H "Authorization: Bearer ${{ secrets.HOME_SERVER_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d "{
            \"event_type\": \"service-updated\",
            \"client_payload\": {
              \"service\": \"resource\",
              \"sha\": \"${GITHUB_SHA}\"
            }
          }"
